---

- name: Configure EC2 instance
  hosts: ec2
  connection: ssh
  sudo: true


  tasks:
  - name: Update the machine
    command: sudo apt-get clean && update -y
    
  - name: Installing essentials
    command: apt-get install apt-transport-https ca-certificates curl software-properties-common -y
      
  - name: Installing Curl
    command: apt-get install curl -y
  
  - name: Installing docker
    command: apt install docker.io -y

  - name: Adding user to group
    command: sudo usermod -aG docker ${USER}

  - name: Restarting docker service
    command: sudo service docker restart 

  - name: Updating the machine 2
    command: sudo apt-get update

  - name: Installing Python Pip
    command: sudo apt-get install python-pip python-dev build-essential -y

 - name: Installing Python
    command: sudo apt install python3.8
 
  - name: Installing Docker compose
    command: sudo pip install docker-compose==1.3.0
    
  - name: apt update
    apt: update_cache=yes cache_valid_time=3600
    register: apt_result
    until: apt_result|success
    retries: 3
    delay: 1
    sudo: yes
    ignore_errors: yes

  - name: retry if needed using command apt-get update
    command: apt-get update
    sudo: yes
    when: apt_result|failed

 - name: Copy using inline content
   ansible.builtin.copy:
    content: "version: '3.7'

services:
  web:
    image: django:latest
    command: gunicorn hello_django.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    ports:
    - '8000:8000'
    environment:
      SQL_ENGINE: django.db.backends.postgresql
      SQL_DATABASE: hello_django #  change this 
      SQL_USER: hello_django  # change this 
      SQL_PASSWORD: hello_django  # change this 
      SQL_HOST: db # change this 
      SQL_PORT: 5432  # change this 

volumes:
  static_volume:
  media_volume:"
    dest: /tmp/syntax/docker-compose.yml

  - name: Running docker-compose.yml
    command: sudo docker-compose -f /tmp/syntax/docker-compose.yml up -d		    
